name: build react application

on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build
        run: |
          git config --global core.ignorecase true
          cd frontend
          npm ci
          npm run build --if-present
