name: auto-format
on:
  pull_request:
    branches:
      - dev

jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: rome check backend
        working-directory: backend
        run: npx rome check src prisma --apply
      - name: rome format backend
        working-directory: backend
        run: npx rome format src prisma --write
      # - name: rome check frontend
      #   working-directory: frontend
      #   run: npx rome check src --apply
      - name: rome format frontend
        working-directory: frontend
        run: npx rome format src --write
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated changes"
          git push
